### ISSUE TITLE
Timing problems

### ISSUE THREAD

**Issue by plusInfinity** [ftrvxmtrx/split2flac#27]
Hi, 
I noticed that split2flac doesn't cut my files precisely. Usually I have a warning like:
shnsplit: warning: rounding 4:42.050 (offset: 49753620) to nearest sector boundary (offset: 49754208)

I omitted the usage of cuebreakpoints and this actually helped. Here is my patch against 114 version:

--- /usr/bin/split2flac	2015-01-17 15:52:43.000000000 +1100
+++ split2flac	2015-01-17 15:51:18.321760070 +1100
@@ -503,10 +503,7 @@
 		esac
 
 		# split to tracks
-		# sed expression is a fix for "shnsplit: error: m:ss.ff format can only be used with CD-quality files"
-		cuebreakpoints "${CUE}" 2>/dev/null | \
-			sed 's/$/0/' | \
-			shnsplit -O never -o "${ENC}" -d "${OUT}" -t "%n" "${FILE}"
+		shnsplit -O never -f "${CUE}" -o "${ENC}" -d "${OUT}" -t "%n" "${FILE}"
 		if [ $? -ne 0 ]; then
 			emsg "Failed to split\n"
 			return 1

**Comment by tvdstaaij** [comment]
Wanted to try this patch but it's unusable because it's not in a markdown code block. I'll leave this here for future visitors:
```
--- /usr/bin/split2flac	2015-01-17 15:52:43.000000000 +1100
+++ split2flac	2015-01-17 15:51:18.321760070 +1100
@@ -503,10 +503,7 @@
 		esac
 
 		# split to tracks
-		# sed expression is a fix for "shnsplit: error: m:ss.ff format can only be used with CD-quality files"
-		cuebreakpoints "${CUE}" 2>/dev/null | \
-			sed 's/$/0/' | \
-			shnsplit -O never -o "${ENC}" -d "${OUT}" -t "%n" "${FILE}"
+		shnsplit -O never -f "${CUE}" -o "${ENC}" -d "${OUT}" -t "%n" "${FILE}"
 		if [ $? -ne 0 ]; then
 			emsg "Failed to split\n"
 			return 1
```

**Comment by tvdstaaij** [comment]
Does anyone know what side effects / downsides this change would possibly have? I assume the cuebreakpoints input was used for a reason.

**Comment by ftrvxmtrx** [comment]
@tvdstaaij it was so long ago I don't even remember. It's possible that I didn't even know shnsplit can parse cue sheets on its own. If there will any bug report associated with the change (I incorporated it in the #28 fix) I'll have to revisit. For now it should be fine.

**Comment by haplo** [comment]
I'm seeing the `shnsplit: error: m:ss.ff format can only be used with CD-quality files` error when trying to use split2flac with a multi-track CUE and FLAC file. Should I open a new issue or provide more information here?
