### ISSUE TITLE
Script cannot handle cue files with a single track

### ISSUE THREAD

**Issue by tvdstaaij** [ftrvxmtrx/split2flac#28]
I use split2flac for mass splitting of albums under a supervisor script, processing the tree one directory of albums at a time. There are a number of albums in the directory tree with only one track. They have a cue file like this:

```
PERFORMER "someperformer"
TITLE "somealbum"
FILE "somealbum.flac" WAVE
  TRACK 01 AUDIO
    TITLE "sometrack"
    PERFORMER "someperformer"
    INDEX 01 00:00:00
```

This causes the following message to appear when such an album is processed.
```
shnsplit: error: no split points given -- nothing to do
Failed to split
Failed to split "/path/to/somealbum.flac"
```

Afterwards the following message is printed and the process exits with status 3.
```
1 file(s) failed to split (already split?):

[filename]

These files are also listed in split_failed.txt.
```

This is rather problematic for me for two reasons: I have to convert said albums by hand afterwards, and because I use directory input, when my supervisor script sees a non-zero exit status it has to write off the entire directory as failed. Desired behavior would be to just skip the splitting stage and process the whole source file as a single track, using the metadata from track 01 for naming and tags.

**Comment by ftrvxmtrx** [comment]
Thanks for the report, I'll try to make split2flac detect this special case.

**Comment by tvdstaaij** [comment]
Awesome! Tried it with one of the problematic directories and works like a charm. Thank you very much.
